"""Shared fixtures.

Fixture documents are generated by ``tests/make_fixtures.py`` from the valid
example, so they cannot drift away from the schema without the generator being
updated too.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

DATA = Path(__file__).resolve().parent / "data"
EXAMPLES = Path(__file__).resolve().parent.parent / "examples"


def load(name: str) -> dict:
    """Read a fixture document. Test modules that need this define their own copy
    rather than importing it -- `from conftest import ...` only resolves when
    pytest's rootdir is this repository, which is not true when both repos'
    suites are collected together."""
    return json.loads((DATA / name).read_text(encoding="utf-8"))


@pytest.fixture
def data_dir() -> Path:
    return DATA


@pytest.fixture
def examples_dir() -> Path:
    return EXAMPLES


@pytest.fixture
def valid_dataset() -> dict:
    return load("dataset-valid.json")


@pytest.fixture
def valid_calibration() -> dict:
    return json.loads((EXAMPLES / "calibration-fixed.json").read_text(encoding="utf-8"))


@pytest.fixture
def valid_protocol() -> dict:
    return json.loads((EXAMPLES / "protocol-prbs.json").read_text(encoding="utf-8"))
